# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{feeder}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jamie van Dyke"]
  s.date = %q{2009-10-26}
  s.email = %q{jamie@fearoffish.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".autotest",
     ".document",
     ".gitignore",
     "LICENSE",
     "Rakefile",
     "VERSION",
     "features/env.rb",
     "features/feeds.feature",
     "features/step_definitions/feed_steps.rb",
     "feeder.gemspec",
     "lib/feeder.rb",
     "lib/feeder/parser.rb",
     "test/feeder/parser_test.rb",
     "test/feeder_test.rb",
     "test/fixtures/feeds/small/affili.net.xml",
     "test/fixtures/feeds/small/affiliatewindow.xml",
     "test/fixtures/feeds/small/apple.xml",
     "test/fixtures/feeds/small/commissionjunction.xml",
     "test/fixtures/feeds/small/dgmpro.xml",
     "test/fixtures/feeds/small/tradedoublerquality.xml",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/fearoffish/feeder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TODO}
  s.test_files = [
    "test/feeder/parser_test.rb",
     "test/feeder/puller_test.rb",
     "test/feeder_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<feed_parser>, [">= 0"])
      s.add_runtime_dependency(%q<feed_puller>, [">= 0"])
    else
      s.add_dependency(%q<feed_parser>, [">= 0"])
      s.add_dependency(%q<feed_puller>, [">= 0"])
    end
  else
    s.add_dependency(%q<feed_parser>, [">= 0"])
    s.add_dependency(%q<feed_puller>, [">= 0"])
  end
end
