# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{feeder}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jamie van Dyke"]
  s.date = %q{2009-10-30}
  s.email = %q{jamie@fearoffish.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".autotest",
     ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "feeder.gemspec",
     "lib/feeder.rb",
     "lib/feeder/puller.rb",
     "lib/feeder/templates/default.xsl.erb",
     "lib/feeder/translator.rb",
     "test/feeder/puller_test.rb",
     "test/feeder/translator_test.rb",
     "test/fixtures/feeds/affili.net/config.yml",
     "test/fixtures/feeds/affili.net/expected.xsl",
     "test/fixtures/feeds/affili.net/output.xml",
     "test/fixtures/feeds/affili.net/source.xml",
     "test/fixtures/feeds/dgm/config.yml",
     "test/fixtures/feeds/dgm/expected.xsl",
     "test/fixtures/feeds/dgm/output.xml",
     "test/fixtures/feeds/dgm/source.xml",
     "test/fixtures/feeds/other/affiliatewindow.xml",
     "test/fixtures/feeds/other/commissionjunction.xml",
     "test/fixtures/feeds/other/dgmpro.xml",
     "test/fixtures/feeds/tradedoubler/config.yml",
     "test/fixtures/feeds/tradedoubler/expected.xsl",
     "test/fixtures/feeds/tradedoubler/output.xml",
     "test/fixtures/feeds/tradedoubler/source.xml",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/fearoffish/feeder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Feeder is a set of classes for pulling and translating feeds in to a format we expect.}
  s.test_files = [
    "test/feeder/iterator_test.rb",
     "test/feeder/puller_test.rb",
     "test/feeder/translator_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-xslt>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<ruby-xslt>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<ruby-xslt>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

