# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "feeder"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jamie van Dyke"]
  s.date = "2011-11-23"
  s.email = "jamie@boxedup.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "feeder.gemspec",
    "lib/feeder.rb",
    "lib/feeder/iterator.rb",
    "lib/feeder/puller.rb",
    "lib/feeder/templates/default.xsl.erb",
    "lib/feeder/translator.rb",
    "test/feeder/iterator_test.rb",
    "test/feeder/puller_test.rb",
    "test/feeder/translator_test.rb",
    "test/fixtures/feeds/affili.net/config.yml",
    "test/fixtures/feeds/affili.net/expected.xsl",
    "test/fixtures/feeds/affili.net/output.xml",
    "test/fixtures/feeds/affili.net/source.xml",
    "test/fixtures/feeds/buy.at/config.yml",
    "test/fixtures/feeds/buy.at/expected.xsl",
    "test/fixtures/feeds/buy.at/output.xml",
    "test/fixtures/feeds/buy.at/source.xml",
    "test/fixtures/feeds/dgm/config.yml",
    "test/fixtures/feeds/dgm/expected.xsl",
    "test/fixtures/feeds/dgm/output.xml",
    "test/fixtures/feeds/dgm/source.xml",
    "test/fixtures/feeds/other/affiliatewindow.xml",
    "test/fixtures/feeds/other/commissionjunction.xml",
    "test/fixtures/feeds/other/dgmpro.xml",
    "test/fixtures/feeds/tradedoubler/config.yml",
    "test/fixtures/feeds/tradedoubler/expected.xsl",
    "test/fixtures/feeds/tradedoubler/output.xml",
    "test/fixtures/feeds/tradedoubler/source.xml",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/boxedup/feeder"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Feeder is a set of classes for pulling and translating feeds in to a format we expect."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-xslt>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<ruby-xslt>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<ruby-xslt>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

